sub main(_args as dynamic)
    store = Prairie.Store.createRegistryStore("prairie")
    Prairie.Persist.ensureStorageSchema(store)

    screen = CreateObject("roSGScreen")
    port = CreateObject("roMessagePort")
    screen.setMessagePort(port)
    scene = screen.CreateScene("MainScene")
    screen.show()
    scene.setFocus(true)

    while true
        msg = wait(0, port)
        if type(msg) = "roSGScreenEvent"
            if msg.isScreenClosed()
                return
            end if
        end if
    end while
end sub

